### ISSUE TITLE
crashes for me

### ISSUE THREAD

**Issue by nrempel** [gschier/speedpack#1]
homepage-new git:(master) ✗ speedpack . -o out
packing [##------------------] 9%
undefined:1553
    throw new JS_Parse_Error(message, filename, line, col, pos);
    ^
Error
    at new JS_Parse_Error (eval at <anonymous> (/usr/local/lib/node_modules/speedpack/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1545:18)
    at js_error (eval at <anonymous> (/usr/local/lib/node_modules/speedpack/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1553:11)
    at croak (eval at <anonymous> (/usr/local/lib/node_modules/speedpack/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2092:9)
    at token_error (eval at <anonymous> (/usr/local/lib/node_modules/speedpack/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2100:9)
    at unexpected (eval at <anonymous> (/usr/local/lib/node_modules/speedpack/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2106:9)
    at expr_atom (eval at <anonymous> (/usr/local/lib/node_modules/speedpack/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2621:13)
    at maybe_unary (eval at <anonymous> (/usr/local/lib/node_modules/speedpack/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2795:19)
    at expr_ops (eval at <anonymous> (/usr/local/lib/node_modules/speedpack/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2830:24)
    at maybe_conditional (eval at <anonymous> (/usr/local/lib/node_modules/speedpack/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2835:20)
    at maybe_assign (eval at <anonymous> (/usr/local/lib/node_modules/speedpack/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2859:20)

**Comment by gschier** [comment]
@nrempel can you give it another shot with the latest version on NPM?

**Comment by nrempel** [comment]
will do tonight
